spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/ativodb?authSource=admin&authMechanism=SCRAM-SHA-1

  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
